df <- read.table("household_power_consumption.txt", na.strings = "?",sep = ";",header = TRUE)
df1 <- subset(df, ((Date == "1/2/2007") | (Date == "2/2/2007")))
df1$DTime <- strptime(paste(df1$Date, df1$Time), format="%Y-%m-%d %H:%M:%S")
with(df1, hist(Global_active_power, col="red", breaks=15, xlab="Global Active Power (kilowatts)", main="Global Active Power"))
dev.copy(png,'plot1.png',  width = 480, height = 480)
dev.off()