df <- read.table("household_power_consumption.txt", na.strings = "?",sep = ";",header = TRUE)
df1 <- subset(df, ((Date == "1/2/2007") | (Date == "2/2/2007")))
df1$DTime <- strptime(paste(df1$Date, df1$Time), format="%d/%m/%Y %H:%M:%S")
with(df1, plot(DTime, Global_active_power, type="l", xlab="", ylab="Global Active Power (in kilowatts)"))
dev.copy(png,'plot2.png',  width = 480, height = 480)
dev.off()