df <- read.table("household_power_consumption.txt", na.strings = "?",sep = ";",header = TRUE)
df1 <- subset(df, ((Date == "1/2/2007") | (Date == "2/2/2007")))
df1$DTime <- strptime(paste(df1$Date, df1$Time), format="%d/%m/%Y %H:%M:%S")
par(mfrow=c(2,2))
with(df1, plot(DTime, Global_active_power, type="l", xlab="", ylab="Global Active Power"))
with(df1, plot(DTime, Voltage, type="l", xlab="datetime", ylab="Voltage"))
plot(df1$DTime, df1$Sub_metering_1, type="l", ylab="Energy sub metering", xlab="")
lines(df1$DTime, df1$Sub_metering_2, col="red")
lines(df1$DTime, df1$Sub_metering_3, col="blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=c(1,1,1), col=c("black","red", "blue"))
with(df1, plot(DTime, Global_reactive_power, type="l",lwd=0.5, xlab="datetime", ylab="Global_reactive_power"))
dev.copy(png,'plot4.png',  width = 480, height = 480)
dev.off()